---
image: gcc

Linux_Secured:
  stage: build
  before_script:
    - apt update && apt -y install make autoconf
    - set -o pipefail
    - export VERBOSE=false
    - export CCACHE_DISABLE=false
  script:
    - cd tests
    - ./auto_build.sh linux
Linux_Secured_Test:
  stage: build
  before_script:
    - apt update && apt -y install make autoconf
    - set -o pipefail
    - export VERBOSE=false
    - export CCACHE_DISABLE=false
  script:
    - cd tests
    - ./auto_build.sh linux_test
Linux_Unsecured:
  stage: build
  before_script:
    - apt update && apt -y install make autoconf
    - set -o pipefail
    - export VERBOSE=false
    - export CCACHE_DISABLE=false
  script:
    - cd tests
    - ./auto_build.sh linux_unsecured
Linux_Unsecured_Test:
  stage: build
  before_script:
    - apt update && apt -y install make autoconf
    - set -o pipefail
    - export VERBOSE=false
    - export CCACHE_DISABLE=false
  script:
    - cd tests
    - ./auto_build.sh linux_unsecured_test
