---
image: gcc:9.3.0

.Linux_Secured_Test:
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  stage: build
  before_script:
    - apt update && apt -y install make autoconf
    - set -o pipefail
    - export VERBOSE=false
    - export CCACHE_DISABLE=false
  script:
    - cd port/linux
    - make DYNAMIC=1 IPV4=1 TCP=1 SECURE=1 test

.Linux_Unsecured_Test:
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  stage: build
  before_script:
    - apt update && apt -y install make autoconf
    - set -o pipefail
    - export VERBOSE=false
    - export CCACHE_DISABLE=false
  script:
    - cd port/linux
    - make DYNAMIC=1 IPV4=1 TCP=1 SECURE=0 test

Android_build:
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  stage: build
  image: gitlab.iotivity.org:5050/iotivity/iotivity-lite
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin 
  script:
    - cd port/android
    - make DYNAMIC=1 TCP=1 IPV4=1 SECURE=1 PKI=1 CLOUD=1 JAVA=1 DEBUG=0
after_script:
    - docker logout
.whitespace_and_doxygen:
  variables:
    GIT_SUBMODULE_STRATEGY: none
  stage: build
  before_script:
    - apt update && apt -y install make autoconf doxygen clang-format
  script:
    - clang-format --version
    - doxygen --version
    - cp tools/_clang-format _clang-format
    - cp tools/whitespace_commit_checker.sh whitespace_commit_checker.sh
    - ./whitespace_commit_checker.sh
    - cd tools
    - ./build_doc.sh
    
